# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'moody-lottie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for moody-lottie

pod 'lottie-ios'

  target 'moody-lottieTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'moody-lottieUITests' do
    # Pods for testing
  end

end
